title: saltfactory's blog
email: saltfactory@gmail.com
#description: ""
base_url: ""
url: "http://blog.saltfactory.net"

excerpt_separator : <!--more-->

paginate: 5

google_analytics : 'UA-8647285-2'

twitter_username: saltfactory
github_username:  saltfactory
facebook_username: salthub
disqus_shortname: saltfactoryblog

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough"]

# highlighter: pygments
permalink: none

# safe: false # if using alias is safe:false
#safe: true
#lsi: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-feed
  # - jekyll-img-converter
  # - jekyll-coffeescript
